export const languages = {
    english: {
        hello: 'hello',
        register_title1: 'Register to be',
        register_title2: 'always upto date',
        your_email: 'Your email',
        your_password: 'Your password',
        confirm_password: 'Confirm password',
        register_now: 'Register Now',
        without_reg: 'Continue Without Registration',
        search: 'Search',
        concerts: 'Concerts',
        festivals: 'Festival',
        theater: 'Theater',
        for_children: 'For children',
        live: 'LIVE',
        now_on_air: 'Now on air',
        setting_panel: 'Setting panel',
        profile: 'Profile',
        notification: 'Notification',
        artist_vol: 'Artist Volume',
        audience_vol: 'Audience volume',
        dark_mode: 'Dark mode',
        language: 'Language',
        privacy: 'Privacy',
        help: 'Help',
        log_out: 'Log Out',
        on: 'On',
        off: 'Off',
        video_formats: 'Video is available in 3 formats',
        watch_now: 'Watch Now',
        disable_aud: 'Disable audience interaction',
        message: 'Message',
        
    },
    franch: {
        hello: 'hello',
        register_title1: 'Inscrivez-vous pour être',
        register_title2: 'toujours à jour',
        your_email: 'Votre e-mail',
        your_password: 'Votre mot de passe',
        confirm_password: 'Confirmez le mot de passe',
        register_now: `S'inscrire maintenant`,
        without_reg: 'Continuer sans inscription',
        search: 'Chercher',
        concerts: 'Concerts',
        festivals: 'Festival',
        theater: 'Théâtre',
        for_children: 'Pour les enfants',
        live: 'HABITENT',
        now_on_air: `Maintenant à l'antenne`,
        setting_panel: 'Panneau de réglage',
        profile: 'Profil',
        notification: 'Notification',
        artist_vol: `Volume de l'artiste`,
        audience_vol: `Volume d'audience`,
        dark_mode: 'Mode sombre',
        language: 'Langue',
        privacy: 'Intimité',
        help: 'Aider',
        log_out: 'Se déconnecter',
        on: 'au',
        off: 'Désactivé',
        video_formats: 'La vidéo est disponible en 3 formats',
        watch_now: 'Regarde maintenant',
        disable_aud: `Désactiver l'interaction avec l'audience`,
        message: 'Un message',

    }
}